services:
  # Streamlit UI Service
  streamlit:
    build:
      context: ..
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://fastapi:8000
    volumes:
      - ../app:/app
    depends_on:
      - fastapi
    networks:
      - kg-network
    restart: unless-stopped

  # FastAPI Backend Service
  fastapi:
    build:
      context: ..
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RDFLIB_STORE_URI=sqlite:///./data/kg.db
      - RDFLIB_GRAPH_IDENTIFIER=kg
      - RDFLIB_NAMESPACE_PREFIX=http://example.org/kg/
      - CACHE_DIR=/app/data/cache
      - LOCK_DIR=/app/data/locks
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../requirements.txt:/app/requirements.txt
    networks:
      - kg-network
    restart: unless-stopped



  # 캐시 및 상태 관리는 이제 diskcache (파일 기반)으로 처리됩니다
  # Redis 서비스는 더 이상 필요하지 않습니다

# Redis 볼륨은 더 이상 필요하지 않습니다 (diskcache는 로컬 파일 시스템 사용)
# volumes:

networks:
  kg-network:
    driver: bridge